### ISSUE TITLE
Stars rating keyboard shortcut not functioning

### ISSUE THREAD

**Issue by Dave22152** [aurelienpierreeng/ansel#8]
I understand that you're revamping the stars rating approach.  Your forked version (as of 3.9.0+1781~gb8cdc71b6-dirty on Windows 11) seems to have disabled the keyboard shortcut for ratings.  For example, I select an image and type a "3" then a message will pop-up stating "3 not applied".  I don't know if this is intentional, but the keyboard shortcut was a bit of a time saver.  Good luck with your efforts!

**Comment by jorgesate** [comment]
That happend to me even in (main) darktable. I just needed to remap every number again to make it work.
![imagen](https://user-images.githubusercontent.com/23036943/176115938-28ca2c68-4acc-4961-8474-4e2b87487356.png)

Hope this gets you around, at least.

**Comment by Dave22152** [comment]
Thanks!

Dave G.

**Comment by aurelienpierre** [comment]
Fixed ?

**Comment by Dave22152** [comment]
I recreated the shortcuts on my machine, but without any changes to the code then I’d expect that the original problem still persists. I can try with a fresh build when I get back home in a couple of weeks. 

Dave G.

**Comment by aurelienpierre** [comment]
That's one of the perks of the new MIDI shit. Previously, keyboard shortcuts used Gtk accelerators. Now, that got replaced by something custom. Gtk identifies numeric keys the same, whether they are input from numpad or text pad. The new stuff doesn't. That's progress.

**Comment by Dave22152** [comment]
I can see how new interfaces could mess with legacy keyboard actions. The shortcuts do work under DT 4.0, which made me consider that something changed under your fork.

Reassigning the shortcut is a viable workaround, but the question of the missing shortcuts has already come up in the forum and I’d expect more confusion unless the functionality is restored in the program or at least addressed in documentation.

**Comment by aurelienpierre** [comment]
> For those who extensively use keyboard shortcuts, the ability to assign numpad keys separately from the "ordinary" number keys is indeed progress. The old behavior can "easily" be restored by explicitly recreating the double mapping. 

The fact that a "4" works differently depending on where it's typed is a regression, period. Otherwise, we wouldn't label keys on keyboards, we would just use their coordinates.

This kind of comment makes me very happy to not have to deal with your bullshit anymore. Keep developing headless libraries, don't mess up with UX.

**Comment by Dave22152** [comment]
> Fixed ?

I just build a fresh (Windows) copy and the short cuts are still missing.  Like I said earlier, remapping the key stroke is a good work around, so I suggest closing the issue if you don't see it as a priority.

**Comment by dterrahe** [comment]
https://github.com/darktable-org/darktable/pull/12351

**Comment by aurelienpierre** [comment]
Anyway, I need to make numeric keys behave the same for the whole keyboard. The current behaviour is unacceptable and breaks a very basic user expectation for the sake of allowing deviant niche uses from a bunch of dudes who spend more time reading config files than editing actual pictures. 

It is expected that users who don't want the numpad to behave as a numpad hit the num_lock key. That is, for the rest of the world who work **with computers** instead of **for computers**.

**Comment by aurelienpierre** [comment]
Fixed.

**Comment by Dave22152** [comment]
Great, thanks!

 

Dave G.

**Comment by aurelienpierre** [comment]
I just went one step further today. All numpad events will be simple remapped to regular key strokes. Enter will be enter no matter where you type it, numbers will just be numbers, etc. 

You know, like in any application. 🙄

**Comment by Dave22152** [comment]
Well, that’s excellent and thanks again.

 

On a side note, given that you’re off the PIXLS site is there a place where people can ask you questions concerning your modules?

 

Dave G.

**Comment by aurelienpierre** [comment]
Yes : https://photo.aurelienpierre.com/private-lessons-on-retouching-with-darktable/?lang=en

**Comment by nitschis** [comment]
Is this broken again with the newest release?

I don't have numpad and I have already tried resetting the star shortcuts, but no matter what I do, stars a not set with my number keys.
